name: Build windows Stanc

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml.5.0.0,ocaml-option-mingw
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2

      - run: opam pin -y core v0.15.1 --no-action
      - run: opam install -y dune core.v0.15.1 menhir.20210929 ppx_deriving.5.2.1 fmt.0.9.0 yojson.1.7.0
      
      - name: Check out Stanc3
        uses: actions/checkout@v3
        with:
          repository: stan-dev/stanc3
          ref: "ocaml-5"
          path: stanc
      
      - run: cd stanc && opam exec -- dune build
      
      - name: Upload Windows stanc
        uses: actions/upload-artifact@v2
        with:
          name: windows-stanc
          path: stanc/_build_/default/src/stanc/stanc.exe
