name: Build windows Stanc

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "4.14.1"

      - run: opam install -y dune core menhir ppx_deriving fmt yojson
      
      - name: Check out Stanc3
        uses: actions/checkout@v4
        with:
          repository: stan-dev/stanc3
          path: stanc
      
      - run: cd stanc && opam exec -- dune build
      - run: Get-ChildItem -Recurse

      - name: Upload Windows stanc
        uses: actions/upload-artifact@v4
        with:
          name: windows-stanc
          path: ./stanc/_build/default/src/stanc/stanc.exe
