name: Build windows Stanc

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml.5.0.0,ocaml-option-mingw

      - run: opam pin -y core v0.16.1 --no-action
      - run: opam install -y dune core.v0.16.1 menhir.20210929 ppx_deriving.5.2.1 fmt.0.9.0 yojson.1.7.0
      
      - name: Check out Stanc3
        uses: actions/checkout@v4
        with:
          repository: stan-dev/stanc3
          path: stanc
      
      - run: cd stanc && opam exec -- dune build
      - run: Get-ChildItem -Recurse

      - name: Upload Windows stanc
        uses: actions/upload-artifact@v4
        with:
          name: windows-stanc
          path: ./stanc/_build/default/src/stanc/stanc.exe
